### ISSUE TITLE
Compilation error on Windows 10 + vc15

### ISSUE THREAD

**Issue by QuantScientist** [podgorskiy/bimpy#2]
Hi,
I followed your instructions to the point,  however I get this error:
![image](https://user-images.githubusercontent.com/18743986/41235326-402e3e5a-6d97-11e8-8b46-815a71c236d6.png)

Can you help?

**Comment by podgorskiy** [comment]
It happened due to the changes in https://github.com/KhronosGroup/OpenGL-Registry/pull/183
Fixed in gl3w in https://github.com/skaslev/gl3w/commit/99ed321100d37032cb6bfa7dd8dea85f10c86132

I'll update gl3w soon.

**Comment by podgorskiy** [comment]
Fixed in 179cc610ee3e9cc5c30806954f4e503a378abb3c
