### ISSUE TITLE
Throw exception if run on headless machine without system X

### ISSUE THREAD

**Issue by podgorskiy** [podgorskiy/bimpy#32]
Currently, if run on a headless linux machine, it results in a segmentation fault.
Should throw an exception with a comment about the problem.
A silent crash creates a lot of confusion.

![image](https://user-images.githubusercontent.com/3229783/80868861-0f0b2780-8c6b-11ea-9d12-35cdfc2f03bf.png)

https://github.com/podgorskiy/ALAE/issues/25
https://github.com/podgorskiy/ALAE/issues/22
https://github.com/podgorskiy/ALAE/issues/13
 https://github.com/podgorskiy/ALAE/issues/12

**Comment by udithhaputhanthri** [comment]
@podgorskiy 
Hi, Thanks for the nice repository. I would like to know how to solve this exception. I was trying to work with bimpy on google Colab but it throwing the above issue. 


Actually, I was trying to run ALAE on colab.
