### ISSUE TITLE
How can bimpy import unicode?

### ISSUE THREAD

**Issue by 529324416** [podgorskiy/bimpy#33]
how to show chinese or japanese with your package ?

**Comment by podgorskiy** [comment]
Japanese or Chinese should not be a problem, you need to load the font with the needed glyphs.
On the other hand, Arabic, Thai, and others that require complex text shaping likely won't be supported.

I might add a section on how to use other fonts to the readme file.

**Comment by podgorskiy** [comment]
This should work now, please see:
https://github.com/podgorskiy/bimpy#non-english-text
![](https://user-images.githubusercontent.com/3229783/101281665-4b24de80-379e-11eb-8170-fe09d6bfa894.png)

**Comment by Shoulder404** [comment]
run this demo have some problem

urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by Mayorc1978** [comment]
> This should work now, please see: https://github.com/podgorskiy/bimpy#non-english-text ![](https://user-images.githubusercontent.com/3229783/101281665-4b24de80-379e-11eb-8170-fe09d6bfa894.png)

`bp.load_fonts(chinese=True, latin_ext=True, japanese=True, cyrillic=True)`

This line of code will crash the program, giving this error, and by the way the demo file doesn't work either (tested on Windows10):
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

I've also tried using "\u" or "\x" strings to have special characters but apart from trademark and some other symbols, it looks like most symbols are not supported, for instance I've tried to get ↓ ⇓ or ▼ and they don't work, they show as '?'
How do I solve and import all of the symbols correctly?
